package:
    name: cyberpandas
    version: {{ environ.get('GIT_DESCRIBE_TAG', '0.1.0') }}

build:
    number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
    script: python setup.py install --single-version-externally-managed --record=record.txt

source:
    path: {{ environ.get("TRAVIS_BUILD_DIR", "../../") }}

requirements:
  build:
    - python
    - setuptools_scm
    - setuptools >=3.3

  run:
    - python
    - setuptools >=3.3
    - pandas
    - ipaddress # [py27]

test:
  imports:
    - cyberpandas

about:
  home: https://github.com/continuumio/cyberpandas
  license: BSD
