package:
    name: cyberpandas
    version: 0.3.0

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt

source:
    path: {{ environ.get("TRAVIS_BUILD_DIR", "../../") }}

requirements:
  build:
    - python
    - setuptools_scm
    - setuptools >=3.3

  run:
    - ipaddress # [py27]
    - pandas >=0.23.0
    - python
    - setuptools >=3.3

test:
  imports:
    - cyberpandas

about:
  home: https://github.com/continuumio/cyberpandas
  license: BSD
