name: cyberpandas-docs
channels:
  - intake
  - defaults
dependencies:
  - coverage
  - flake8
  - ipython
  - matplotlib
  - numba
  - numpy
  - numpydoc
  - pandas
  - pytest
  - pytest-cov
  - python=3.6
  - six
  - sphinx
  - sphinx_rtd_theme
