name: cyberpandas-docs
channels:
  - defaults
  - conda-forge/label/rc
dependencies:
  - coverage
  - flake8
  - ipython
  - matplotlib
  - numpy
  - numpydoc
  - pandas >=0.23.0rc2
  - pytest
  - pytest-cov
  - python=3.6
  - six
  - sphinx
  - sphinx_rtd_theme
