package:
    name: pandas_ip
    version: {{ environ.get('GIT_DESCRIBE_TAG','') }}

build:
    number: 0

source:
    git_url: ../../

requirements:
  build:
    - python
    - setuptools_scm
    - setuptools >=3.3

  run:
    - python
    - setuptools >=3.3
    - pandas

test:
  imports:
    - pandas_ip

about:
  home: https://github.com/continuumio/pandas-ip
  license: BSD
