package:
    name: pandas_ip
    version: {{ environ.get('GIT_DESCRIBE_TAG','') }}

build:
    number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
    {% if GIT_DESCRIBE_NUMBER|int == 0 %}string: np{{ CONDA_NPY }}py{{ CONDA_PY }}_0
    {% else %}string: np{{ CONDA_NPY }}py{{ CONDA_PY }}_{{ GIT_BUILD_STR }}{% endif %}

source:
    git_url: ../../

requirements:
  build:
    - python
    - setuptools_scm
    - setuptools >=3.3

  run:
    - python
    - setuptools >=3.3
    - pandas

test:
  imports:
    - pandas_ip

about:
  home: https://github.com/continuumio/pandas-ip
  license: BSD
