package:
    name: pandas
    version: 0.23.0

build:
    number: 2

source:
    git_url: https://github.com/pandas-dev/pandas

requirements:
  build:
    - python
    - cython
    - numpy
    - setuptools >=3.3
    - python-dateutil >=2.5.0
    - pytz

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - python-dateutil >=2.5.0
    - pytz

test:
  imports:
    - pandas.core.arrays.base

about:
  home: http://pandas.pydata.org
  license: BSD
