package:
    name: pandas
    version: {{ environ.get('GIT_DESCRIBE_TAG','').replace('v', '', 1) }}

build:
    number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
    {% if GIT_DESCRIBE_NUMBER|int == 0 %}string: np{{ CONDA_NPY }}py{{ CONDA_PY }}_0
    {% else %}string: np{{ CONDA_NPY }}py{{ CONDA_PY }}_{{ GIT_BUILD_STR }}{% endif %}

source:
    git_url: {{ environ.get('PANDAS_ROOT') }}

requirements:
  build:
    - python
    - cython
    - {{ pin_compatible('numpy') }}
    - setuptools >=3.3
    - python-dateutil >=2.5.0
    - pytz

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - python-dateutil >=2.5.0
    - pytz

test:
  imports:
    - pandas

about:
  home: http://pandas.pydata.org
  license: BSD
