package:
    name: pandas
    version: {{ environ.get('GIT_DESCRIBE_TAG','').replace('v', '', 1) }}

build:
    number: 0

source:
    git_url: https://github.com/pandas-dev/pandas
    patches:
        - 0001-ENH-non-interval-changes.patch

requirements:
  build:
    - python
    - cython
    - {{ pin_compatible('numpy') }}
    - setuptools >=3.3
    - python-dateutil >=2.5.0
    - pytz

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - python-dateutil >=2.5.0
    - pytz

test:
  imports:
    - pandas.core.arrays.base

about:
  home: http://pandas.pydata.org
  license: BSD
