package:
    name: pandas
    version: {{ environ.get('GIT_DESCRIBE_TAG', 'v0.23.0').replace('v', '', 1) }}

build:
    number: {{ environ.get('GIT_DESCRIBE_TAG', 0) }}

source:
    git_url: https://github.com/pandas-dev/pandas

requirements:
  build:
    - python
    - cython
    - numpy
    - setuptools >=3.3
    - python-dateutil >=2.5.0
    - pytz

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - python-dateutil >=2.5.0
    - pytz

test:
  imports:
    - pandas.core.arrays.base

about:
  home: http://pandas.pydata.org
  license: BSD
